spring:
  application:
    name: chatbot
  ai:
    ollama:
      chat:
        options:
          model: llama3.2
      #base-url: http://localhost:11434 # url when running on local machine
      base-url: http://host.docker.internal:11434 #ollam url when running on docker

logging:
  level:
    org:
      springframework:
        ai: debug
    com:
      ns:
        chatbot: debug
  file:
    path: ${user.dir}${file.separator}logs${file.separator}${spring.application.name}
    name: ${spring.application.name}.log
  include-application-name: true

server:
  port: 8081

openWeather:
  url: ${OPEN_WEATHER_URL:https://api.openweathermap.org/data/2.5/weather}
  apiKey: ${OPEN_WEATHER_URL:XXX}

