spring:
  application:
    name: chatbot
  ai:
    ollama:
      chat:
        options:
          model: llama3.2
      base-url: http://localhost:11434

logging:
  level:
    org:
      springframework:
        ai: debug

server:
  port: 8081