spring:
  application:
    name: chatbot
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/ai
    username: dev_user
    password: dev_password
#  sql:
#    init:
#      schema-locations: classpath:init.sql
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        #max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        remove-existing-vector-store-table: true
        initialize-schema: true
    ollama:
      chat:
        model: llama3.2
      base-url: http://localhost:11434
      embedding:
        model: mxbai-embed-large

  threads:
    virtual:
      enabled: true




logging:
  level:
    org:
      springframework:
        ai: info
  file:
    path: ${user.dir}${file.separator}logs${file.separator}${spring.application.name}
    name: ${spring.application.name}.log
  include-application-name: true

openWeather:
  url: ${OPEN_WEATHER_URL:https://api.openweathermap.org/data/2.5/weather}
  apiKey: ${OPEN_WEATHER_URL:XXXX}

