/*
 * Volvo Group vehicle APIs
 * Volvo Group vehicle API
 *
 * OpenAPI spec version: 1.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.chatbot.usecase.vehicle_fake_data_generator;

import lombok.Builder;

import java.io.Serializable;
import java.util.List;

@Builder
public record Vehicle(String id, String vin, String customerVehicleName,
                      String brand, String productionDate, String type,
                      String model, List<String> possibleFuelType,
                      String emissionLevel,
                      String chassisType, Integer noOfAxles,
                      Integer totalFuelTankVolume,
                      String gearboxType, String bodyType,
                      String registrationNumber) implements Serializable {
}
